### ISSUE TITLE
"Undefined is not a function"

### ISSUE THREAD

**Issue by ThunbergOlle** [Kryzoid/inventory-aggregator#1]
> inventory-aggregator@1.0.0 start C:\Users\Olle\Documents\GitHub\inventory-aggregator
> node inventories.js

(node:3104) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: undefined is not a function
(node:3104) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process wi
th a non-zero exit code.

**Comment by Kryzoid** [comment]
Thanks for your report!

This bug doesn't prevent the script from executing, so I'll leave this issue open but won't be patching it for now.

**Comment by ThunbergOlle** [comment]
The issue was the outdated version of NodeJS that I had. 🤦‍♂️
